UserReservation/Controllers/SignupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UserReservation.Models;

namespace test.Controllers
{
    public class SignupController : Controller
    {
        private URModel _db = new URModel();
        protected override void HandleUnknownAction(string actionName)

        {

            try
            {

                this.View(actionName).ExecuteResult(this.ControllerContext);

            }
            catch (InvalidOperationException ieox)

            {

                ViewData["error"] = "Unknown Action: \"" + Server.HtmlEncode(actionName) + "\"";

                ViewData["exMessage"] = ieox.Message;

                this.View("Error").ExecuteResult(this.ControllerContext);

            }

        }
        // GET: Signup
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SignupSuccess([Bind(Exclude = "Id")] User u)
        {
            if (!ModelState.IsValid)
                return View();

            _db.User.Add(u);
            _db.SaveChanges();

            return View();
        }
     
    }
}

UserReservation/Views/Signup/Index.cshtml
@model UserReservation.Models.User
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Signup</title>
    <style>
        #Signup-div {
            position: absolute;
            left: 37%;
            top: 15%;
            border: lpx solid #000000;
            padding: 10px 10px;
        }

        .field-validation-error {
            color: red;
        }
    </style>
</head>
<body>
    <div id="Signup-div">
        @using (Html.BeginForm("SignupSuccess", "Signup", FormMethod.Post))
        {
            <table>
                <tr>
                    <td></td>
                    <td>
                        Signup
                    </td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.Username)</td>
                    <td>@Html.EditorFor(model => model.Username)</td>
                </tr>
                <tr>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.Password)</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(Model => Model.Password)</td>
                    <td>@Html.EditorFor(model => model.Password)</td>
                </tr>
                <tr>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.Password)</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.Firstname)</td>
                    <td>@Html.EditorFor(model => model.Firstname)</td>
                </tr>

                <tr>
                    <td>@Html.LabelFor(model => model.Lastname)</td>
                    <td>@Html.EditorFor(model => model.Lastname)</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.Street)</td>
                    <td>@Html.EditorFor(model => model.Street)</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.City)</td>
                    <td>@Html.EditorFor(model => model.City)</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.Provin)</td>
                    <td>@Html.DropDownListFor(model => model.Provin,new SelectList(new[] {
                "Nova Scotia",
                "New Brunswick",
                "Prince Edward Island",
                "Newfoundland",
                "Quebec",
                "Ontario",
                "Alberta",
                "Saskatchewan",
                "Manitoba",
                "British Columbia",}))</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.Coun)</td>
                    <td>@Html.DropDownListFor(model => model.Coun, new SelectList(new[] {"Canada",}))</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.Postal)</td>
                    <td>@Html.EditorFor(model => model.Postal)</td>
                </tr>
                <tr>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.Postal, "", new { @class = "text-danger" })</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.Phone)</td>
                    <td>@Html.EditorFor(model => model.Phone)</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.Email)</td>
                    <td>@Html.EditorFor(model => model.Email)</td>
                </tr>
                <tr>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.Email)</td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <input type="submit" name="name" value="Signup">
                        <input type="reset" name="name" value="Clear">
                    </td>
                </tr>
            </table>
        }

    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
</body>
</html>

UserReservation/Views/Signup/SignupSuccess.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SignupSuccess</title>
</head>
<body>
    <div> 
        <h3>Register Successfully!</h3>
        <a href="@Url.Action("Loginout", "Login")">Login again</a>
    </div>
</body>
</html>